spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-client

server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/


info.groupId: @project.groupId@
info.artifactId: @project.artifactId@
info.version: @project.version@


#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
      health:
        show-details: ALWAYS